version: '2'
services:
  wp:
    image: wordpress:5.4.1
    depends_on:
      - db
    volumes:
    #  - ./wp-archive:/wp-archive
      - ./src:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: {app_name}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mvst2021
    networks:
      - {app_name}
    
    ports:
      - {port}:80 # change ip if required
  
  db:
    image: mysql:5.7 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    #ports:
    #  - 127.0.0.1:3306:3306 # change ip if required
    volumes:
      - ./data:/var/lib/mysql
    #  - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: {app_name}
      MYSQL_ROOT_PASSWORD: mvst2021
    networks:
      - {app_name}
networks:
  {app_name}:
